# This workflow checks for updates to OpenCPI.

name: OpenCPI Update Check

on:
  workflow_dispatch:
  push:

env:
  prerel: false

jobs:
  check:
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      status: ${{ steps.semver_compare.outputs.is_greater_b }}
      version: ${{ steps.opencpi_version.outputs.current }}

    steps:

      - name: Local Version
        id: local_version
        uses: lhstrh/action-repo-semver@v1.1.2
        with:
          repo: ${{ github.repository }}

      
      - name: Checkout OpenCPI
        run: git clone https://gitlab.com/opencpi/opencpi.git

      - name: OpenCPI Version
        id: opencpi_version
        uses: lhstrh/action-repo-semver@v1.1.2
        with:
          path: opencpi
      
      - name: Check prerelease
        id: prerel
        if: contains( 'beta', ${{ steps.opencpi_version.outputs.current }})
        run: echo "prerel=true" >> "$GITHUB_ENV"
        
      - name: "Semver Compare"
        id: semver_compare
        uses: YunaBraska/semver-info-action@main
        with:
          semver-a: ${{ steps.local_version.outputs.current }}
          semver-b: ${{ steps.opencpi_version.outputs.current }}

  pr:
    needs: check
    if: needs.check.outputs.status == true

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:

      - name: "Test"
        run: |
          echo "${{ env.prerel }}"
          echo "${{ needs.check.outputs.version }}"
     
